name = "context-worker"
main = "src/index.js"
compatibility_date = "2026-02-01"
dev.port = 8787
[assets]
directory = "./public"

[[kv_namespaces]]
binding = "PASTES"
id = "c582dfcc2f034037beb67658c17bf9a8"